### ISSUE TITLE
Add device type collector

### ISSUE THREAD

**Issue by martin-g** [searchhub/search-collector#4]
Google Analytics allows to get the type of the device: `mobile`, `tablet` and `desktop`.
I think it would be useful to have this information. 
Either BrowserCollector should be extended or a new collector could be introduced.

I am not sure what would be the best way to implement it though. Either from the userAgent, or media query, or browser capabilities, ...

**Comment by toarm** [comment]
We added the capability to track the userAgent in [1.0.0-alpha-17](https://github.com/searchhub/search-collector/releases/tag/1.0.0-alpha-17)

I'll close this issue for now
