### ISSUE TITLE
Documentation about the endpoint API

### ISSUE THREAD

**Issue by schuch** [searchhub/search-collector#5]
Hi,

is there any documentation available, what the calls and payload look like that are sent by the `RestEventWriter` to the backend endpoint?

**Comment by pavelpenchev** [comment]
Hi Markus,

The event payloads are JSON objects ex. `{"type":"instant-search","keywords":"dress","timestamp":1572376401174,"session":"mTfp3ZU"}. `

The collector will:


1. Buffer all incoming events for 1 second
2. Package them as an array ex. `[{"type":"instant-search","keywords":"dress","timestamp":1572376401174,"session":"mTfp3ZU","url":"http://localhost:8080/","ref":""},{"type":"search","keywords":"dress","count":6,"timestamp":1572376402006,"session":"mTfp3ZU","query":"$s=dress/","url":"http://localhost:8080/","ref":""}]`
3. URL encode the array
4. Base64 the result from 3)
5. Request your endpoint via GET like this 
`http://localhost:8080/collector?JTVCJTdCJTIydHlwZSUyMiUzQSUyMmluc3RhbnQtc2VhcmNoJTIyJTJDJTIya2V5d29yZHMlMjIlM0ElMjJkcmVzcyUyMiUyQyUyMnRpbWVzdGFtcCUyMiUzQTE1NzIzNzY0MDExNzQlMkMlMjJzZXNzaW9uJTIyJTNBJTIybVRmcDNaVSUyMiUyQyUyMnVybCUyMiUzQSUyMmh0dHAlM0ElMkYlMkZsb2NhbGhvc3QlM0E4MDgwJTJGJTIyJTJDJTIycmVmJTIyJTNBJTIyJTIyJTdEJTJDJTdCJTIydHlwZSUyMiUzQSUyMnNlYXJjaCUyMiUyQyUyMmtleXdvcmRzJTIyJTNBJTIyZHJlc3MlMjIlMkMlMjJjb3VudCUyMiUzQTYlMkMlMjJ0aW1lc3RhbXAlMjIlM0ExNTcyMzc2NDAyMDA2JTJDJTIyc2Vzc2lvbiUyMiUzQSUyMm1UZnAzWlUlMjIlMkMlMjJxdWVyeSUyMiUzQSUyMiUyNHMlM0RkcmVzcyUyRiUyMiUyQyUyMnVybCUyMiUzQSUyMmh0dHAlM0ElMkYlMkZsb2NhbGhvc3QlM0E4MDgwJTJGJTIyJTJDJTIycmVmJTIyJTNBJTIyJTIyJTdEJTVE`

At you REST endpoint you should grab the GET payload, base64 and url decode and use the JSON. If you clone the project, you can see the above in action by running "npm start", opening http://localhost:8080 and monitoring the CLI and browser console (this runs the small application inside the demo directory)

In theory you can compose a different encoding pipeline by creating your own version of https://github.com/searchhub/search-collector/blob/master/src/main/Collector.js

I hope this helps, I'll add a section in the documentation with the above details.

Best Regards,
Pavel

**Comment by schuch** [comment]
Hi Pavel,
yes this helps a lot to understand how things work 👍
